import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import DynamicSearch from "../components/DynamicSearch";
import CharacterSheet from "../components/CharacterSheet";
import CharacterSheetActions from "../components/CharacterSheetActions";
import { app, database } from "../firebase/clientApp";
import { collection, addDoc, getDocs, query, where } from "firebase/firestore";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

const getWeps = async () => {
	const dbInstance = collection(database, "weapons");
	const q = query(dbInstance, where("Name", ">=", "Sh"));

	const allWeapons = await getDocs(q).then((data) => {
		return data.docs.map((item) => item.data());
	});

	return allWeapons;
};

const getArmor = async () => {
	const dbInstance = collection(database, "armor");
	const q = query(dbInstance, where("Name", ">=", "Ru"));

	const allArmor = await getDocs(q).then((data) => {
		return data.docs.map((item) => item.data());
	});

	return allArmor;
};

const getUsers = async () => {
	const dbInstance = collection(database, "users");

	const allUsers = await getDocs(dbInstance).then((data) => {
		return data.docs.map((user) => user.data());
	});

	return allUsers;
};

export async function getStaticProps() {
	const allWeapons = await getWeps();
	const allUsers = await getUsers();
	const allArmor = await getArmor();

	return {
		props: {
			allWeapons,
			allArmor,
			allUsers,
		},
	};
}

export default function Home({ allWeapons, allUsers, allArmor }) {
	const [selectedSlot, setSelectedSlot] = useState("");
	const [selectedItem, setSelectedItem] = useState({});

	const getSelectedSlot = (slot) => {
		setSelectedSlot(slot);
	};

	const getSelectedItem = (item) => {
		setSelectedItem(item);
	};

	const getItemIcon = (itemId) => {
		const allItems = [...allArmor, ...allWeapons];
		const item = allItems.filter((item) => {
			return item.id == itemId;
		});
		return item[0].icon;
	};

	const getItemName = (itemId) => {
		const allItems = [...allArmor, ...allWeapons];
		const item = allItems.filter((item) => {
			return item.id == itemId;
		});
		return item[0].Name;
	};

	return (
		<div className="w-max m-auto">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<CharacterSheetActions
				getItemIcon={getItemIcon}
				getItemName={getItemName}
				allUsers={allUsers}
			/>
			<div className="flex">
				<CharacterSheet getSelectedSlot={getSelectedSlot} />
				<DynamicSearch
					allWeapons={allWeapons}
					allArmor={allArmor}
					selectedSlot={selectedSlot}
					getSelectedItem={getSelectedItem}
				/>
			</div>
		</div>
	);
}
